[2019-01-28 01:57:28,794] [log.py|__console] [line:40] INFO    : 当前执行测试用例ID-> test_login001.1 ; 测试点-> 手机号和密码为空登录
[2019-01-28 01:57:35,462] [log.py|__console] [line:40] INFO    : 检查点-> 手机号不能为空
[2019-01-28 01:57:35,670] [log.py|__console] [line:40] INFO    : 异常登录，返回实际结果是->: 手机号不能为空
